language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.6"

install:
    - pip install pandas
    - pip install numpy
    - pip install xarray
    - pip install pytz
    - pip install netCDF4

script:
    - cd tests
    - python test.py
    - conda build conda.recipe
    - conda install your-package --use-local
